export const FETCH_CONTACTS = "FETCH_CONTACTS";

export const CREATE_CONTACT = "CREATE_CONTACT";

export const UPDATE_CONTACT = "UPDATE_CONTACT";

export const DELETE_CONTACT = "DELETE_CONTACT";

export const FAVOURITE_CONTACT = "FAVOURITE_CONTACT";
