// mongoose model enums
const ORDER_CREATED = "CREATED";
const ORDER_DISCUSSED = "DISCUSSED";
const ORDER_AGREED = "AGREED";
const ORDER_SIGNED = "SIGNED";

const CONTRACT_CONFIRMED = "CONFIRMED";
const CONTRACT_FULFILLED = "FULFILLED";

const ADMIN_USER = "ADMIN";
const GENERAL_USER = "GENERAL";



module.exports = {
	ORDER_CREATED,
	ORDER_DISCUSSED,
	ORDER_AGREED,
	ORDER_SIGNED,
	CONTRACT_CONFIRMED,
	CONTRACT_FULFILLED,
	ADMIN_USER,
	GENERAL_USER,
};
