// mongoose model enums
const ORDER_PENDING = "PENDING";
const ORDER_CONFIRMED = "CONFIRMED";
const ORDER_FULFILLED = "FULFILLED";

const CONTRACT_CONFIRMED = "CONFIRMED";
const CONTRACT_FULFILLED = "FULFILLED";

const ADMIN_USER = "ADMIN";
const GENERAL_USER = "GENERAL";



module.exports = {
	ORDER_PENDING,
	ORDER_CONFIRMED,
	ORDER_FULFILLED,
	CONTRACT_CONFIRMED,
	CONTRACT_FULFILLED,
	ADMIN_USER,
	GENERAL_USER,
};
