# This is a basic workflow to help you get started with Actions

name: backend api test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.8.0]       
        
    steps:
    - uses: actions/checkout@v1
      
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
        
    - name: Install newman
      run: npm install -g newman
      working-directory: ./backend  

    - name: Install dependencies
      run: npm install cors express mongoose nodemon dotenv bcryptjs jsonwebtoken
      working-directory: ./backend   
      
      
    - name: Run the backend and test api
      run: |
        npm run start &
        sleep 20
        newman run https://api.getpostman.com/collections/17378209-1a91ec5c-f1d9-4a30-b3d5-e6e8c120d14e?apikey=${{ secrets.postmanApiKey }} -e https://api.getpostman.com/environments/17378209-b44603e1-ff21-40a2-bab3-db7bc02e4928?apikey=${{ secrets.postmanApiKey }}
        newman run https://api.getpostman.com/collections/17378209-2635c65f-652e-4a0f-8210-b289a9072821?apikey=${{ secrets.postmanApiKey }} -e https://api.getpostman.com/environments/17378209-b44603e1-ff21-40a2-bab3-db7bc02e4928?apikey=${{ secrets.postmanApiKey }}
        newman run https://api.getpostman.com/collections/17378209-5d09801b-fb73-4f92-b913-48174911ad8f?apikey=${{ secrets.postmanApiKey }} -e https://api.getpostman.com/environments/17378209-b44603e1-ff21-40a2-bab3-db7bc02e4928?apikey=${{ secrets.postmanApiKey }}
        newman run https://api.getpostman.com/collections/17378209-6b3d2ba1-8c1c-44aa-821b-aa6235678bd6?apikey=${{ secrets.postmanApiKey }} -e https://api.getpostman.com/environments/17378209-b44603e1-ff21-40a2-bab3-db7bc02e4928?apikey=${{ secrets.postmanApiKey }}
        newman run https://api.getpostman.com/collections/17378209-964bce0c-d1fd-4199-a6de-d77212592348?apikey=${{ secrets.postmanApiKey }} -e https://api.getpostman.com/environments/17378209-b44603e1-ff21-40a2-bab3-db7bc02e4928?apikey=${{ secrets.postmanApiKey }}
        newman run https://api.getpostman.com/collections/17378209-9859dbef-2d2b-4af8-aeab-1a9673b2dee9?apikey=${{ secrets.postmanApiKey }} -e https://api.getpostman.com/environments/17378209-b44603e1-ff21-40a2-bab3-db7bc02e4928?apikey=${{ secrets.postmanApiKey }}
        newman run https://api.getpostman.com/collections/17378209-dcf4787e-47f6-47b0-a104-b28bea73ef00?apikey=${{ secrets.postmanApiKey }} -e https://api.getpostman.com/environments/17378209-b44603e1-ff21-40a2-bab3-db7bc02e4928?apikey=${{ secrets.postmanApiKey }}
        newman run https://api.getpostman.com/collections/17378209-f222e0b8-8529-4435-9bac-9f65827c60ca?apikey=${{ secrets.postmanApiKey }} -e https://api.getpostman.com/environments/17378209-b44603e1-ff21-40a2-bab3-db7bc02e4928?apikey=${{ secrets.postmanApiKey }}
        
      working-directory: ./backend 
      env:
        DB_URL: "mongodb+srv://admin:admin@scrummasters-it-project.gtsnj.mongodb.net/test?retryWrites=true&w=majority"
        PORT: "5000"
        TEST: "true"
        NODE_ENV: "develop"
        
