# This is a basic workflow to help you get started with Actions

name: frontend compile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.8.0]       
        
    steps:
    - uses: actions/checkout@v1
      
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
        

    - name: Install dependencies
      run: npm install redux react-redux axios react-router-dom react-icons --save redux-devtools-extension jwt-decode react-google-login redux-thunk react-google-button styled-components
      working-directory: ./frontend/my-app
      
    - name: Run the frontend
      run: npm start
      working-directory: ./frontend/my-app
      
      
    
      
      
